# Generated by Django 5.1.15 on 2026-07-24 22:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administration', '0001_initial'),
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=20, unique=True)),
                ('statut_agent', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Agent',
                'db_table': 'securite"."agent',
            },
        ),
        migrations.CreateModel(
            name='Poste',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('structure', models.CharField(max_length=256)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True, unique=True)),
                ('login_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('mairie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='postes', to='administration.mairie')),
            ],
            options={
                'verbose_name': 'Poste',
                'db_table': 'securite"."poste',
            },
        ),
        migrations.CreateModel(
            name='Enregistrement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('datetime_enregistrement', models.DateTimeField()),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enregistrements', to='securite.agent')),
                ('autorisation', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='enregistrement', to='gestion.autorisation')),
                ('poste', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enregistrements', to='securite.poste')),
            ],
            options={
                'verbose_name': 'Enregistrement',
                'db_table': 'securite"."enregistrement',
            },
        ),
    ]
