# Generated by Django 5.1.15 on 2026-07-24 22:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ampliation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Ampliation',
                'db_table': 'gestion"."ampliation',
            },
        ),
        migrations.CreateModel(
            name='CNIB',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('numero', models.CharField(max_length=50, unique=True)),
                ('date_cnib', models.DateField()),
                ('structure', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'CNIB',
                'verbose_name_plural': 'CNIB',
                'db_table': 'gestion"."cnib',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('fichier', models.FileField(upload_to='documents_sources/%Y/%m/')),
                ('type_document', models.CharField(choices=[('word', 'Document Word'), ('pdf', 'PDF'), ('scanne', 'Scan'), ('photo', 'Photo')], max_length=20)),
                ('texte_extrait', models.TextField(blank=True, null=True)),
                ('datetime_upload', models.DateTimeField(auto_now_add=True)),
                ('statut_extraction', models.CharField(choices=[('brute', 'Uploadé, pas encore traité'), ('en_validation', 'Extraction faite, en attente de validation humaine'), ('validee', 'Validé — Autorisation créée'), ('rejetee', 'Rejeté (illisible, doublon...)')], default='brute', max_length=50)),
            ],
            options={
                'verbose_name': 'Document',
                'db_table': 'gestion"."document',
            },
        ),
        migrations.CreateModel(
            name='Habilitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('fonction', models.CharField(max_length=255)),
                ('attribution', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Habilitation',
                'db_table': 'gestion"."habilitation',
            },
        ),
        migrations.CreateModel(
            name='StatutDemandeur',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Statut du demandeur',
                'db_table': 'gestion"."statut_demandeur',
            },
        ),
        migrations.CreateModel(
            name='Demandeur',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True, unique=True)),
                ('profession', models.CharField(max_length=255)),
                ('residence', models.CharField(max_length=100)),
                ('cnib', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='demandeur', to='gestion.cnib')),
                ('statut_demandeur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='demandeurs', to='gestion.statutdemandeur')),
            ],
            options={
                'verbose_name': 'Demandeur',
                'db_table': 'gestion"."demandeur',
            },
        ),
        migrations.CreateModel(
            name='Demande',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('date_demande', models.DateField()),
                ('objet', models.CharField(max_length=255)),
                ('demandeur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='demandes', to='gestion.demandeur')),
            ],
            options={
                'verbose_name': 'Demande',
                'db_table': 'gestion"."demande',
            },
        ),
        migrations.CreateModel(
            name='Autorisation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('numero', models.CharField(max_length=100, unique=True)),
                ('date_autorisation', models.DateField()),
                ('mairie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='autorisations', to='administration.mairie')),
                ('demande', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='autorisations', to='gestion.demande')),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='autorisation', to='gestion.document')),
            ],
            options={
                'verbose_name': 'Autorisation',
                'db_table': 'gestion"."autorisation',
            },
        ),
        migrations.CreateModel(
            name='Personne',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=100)),
                ('profession', models.CharField(blank=True, max_length=255, null=True)),
                ('grade', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Personne',
                'db_table': 'gestion"."personne',
                'constraints': [models.CheckConstraint(condition=models.Q(('profession__isnull', False), ('grade__isnull', False), _connector='OR'), name='chk_personne_profession_ou_grade')],
            },
        ),
        migrations.CreateModel(
            name='StatutDemandeurAutre',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=100)),
                ('datetime_proposition', models.DateTimeField()),
                ('statut', models.CharField(choices=[('en_attente', 'En attente de classement'), ('classee', 'Classée'), ('rejetee', "Rejetée (doublon d'une valeur existante)")], default='en_attente', max_length=50)),
                ('demandeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statut_autre_propositions', to='gestion.demandeur')),
            ],
            options={
                'verbose_name': 'Statut demandeur (proposition Autre)',
                'db_table': 'gestion"."statut_demandeur_autre',
            },
        ),
        migrations.CreateModel(
            name='Signature',
            fields=[
                ('autorisation', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='signature', serialize=False, to='gestion.autorisation')),
                ('habilitation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='signatures', to='gestion.habilitation')),
                ('personne', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='signatures', to='gestion.personne')),
            ],
            options={
                'verbose_name': 'Signature',
                'db_table': 'gestion"."signature',
            },
        ),
        migrations.CreateModel(
            name='AutorisationAmpliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('structure', models.CharField(help_text='Structure exacte destinataire (ex: commissariat précis)', max_length=255)),
                ('ampliation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='autorisations', to='gestion.ampliation')),
                ('autorisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ampliations', to='gestion.autorisation')),
            ],
            options={
                'verbose_name': "Ampliation d'autorisation",
                'db_table': 'gestion"."autorisation_ampliation',
                'constraints': [models.UniqueConstraint(fields=('autorisation', 'ampliation'), name='uq_autorisation_ampliation')],
            },
        ),
    ]
