# Generated by Django 5.1.15 on 2026-07-24 22:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('nom_region', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Région',
                'db_table': 'administration"."region',
            },
        ),
        migrations.CreateModel(
            name='TypeCommune',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Type de commune',
                'db_table': 'administration"."type_commune',
            },
        ),
        migrations.CreateModel(
            name='TypeMairie',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Type de mairie',
                'db_table': 'administration"."type_mairie',
            },
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('nom_province', models.CharField(max_length=50, unique=True)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='provinces', to='administration.region')),
            ],
            options={
                'verbose_name': 'Province',
                'db_table': 'administration"."province',
            },
        ),
        migrations.CreateModel(
            name='Commune',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('nom_commune', models.CharField(max_length=50)),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='communes', to='administration.province')),
                ('type_commune', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='communes', to='administration.typecommune')),
            ],
            options={
                'verbose_name': 'Commune',
                'db_table': 'administration"."commune',
            },
        ),
        migrations.CreateModel(
            name='Mairie',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('nom_mairie', models.CharField(max_length=50)),
                ('commune', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mairies', to='administration.commune')),
                ('type_mairie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mairies', to='administration.typemairie')),
            ],
            options={
                'verbose_name': 'Mairie',
                'db_table': 'administration"."mairie',
            },
        ),
        migrations.AddConstraint(
            model_name='commune',
            constraint=models.UniqueConstraint(fields=('nom_commune', 'province'), name='uq_commune_nom_province'),
        ),
        migrations.AddConstraint(
            model_name='mairie',
            constraint=models.UniqueConstraint(fields=('nom_mairie', 'commune'), name='uq_mairie_nom_commune'),
        ),
    ]
