# Generated by Django 5.1.15 on 2026-07-24 22:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dimension',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Dimension',
                'db_table': 'culture"."dimension',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Genre',
                'db_table': 'culture"."genre',
            },
        ),
        migrations.CreateModel(
            name='ModeAcces',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': "Mode d'accès",
                'db_table': 'culture"."mode_acces',
            },
        ),
        migrations.CreateModel(
            name='Periodicite',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Périodicité',
                'verbose_name_plural': 'Périodicités',
                'db_table': 'culture"."periodicite',
            },
        ),
        migrations.CreateModel(
            name='TypeEspace',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': "Type d'espace",
                'db_table': 'culture"."type_espace',
            },
        ),
        migrations.CreateModel(
            name='TypeManifestation',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Type de manifestation',
                'db_table': 'culture"."type_manifestation',
            },
        ),
        migrations.CreateModel(
            name='Manifestation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('espace', models.CharField(max_length=256)),
                ('duree', models.IntegerField(blank=True, help_text="Durée en heures d'activité effective — indépendante de l'intervalle datetime_debut/datetime_fin, qui peut couvrir plusieurs jours calendaires avec activité partielle.", null=True)),
                ('datetime_debut', models.DateTimeField()),
                ('datetime_fin', models.DateTimeField(blank=True, null=True)),
                ('dimension', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='manifestations', to='culture.dimension')),
                ('genre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='manifestations', to='culture.genre')),
                ('mode_acces', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='manifestations', to='culture.modeacces')),
                ('periodicite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='manifestations', to='culture.periodicite')),
                ('type_espace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='manifestations', to='culture.typeespace')),
                ('type_manifestation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='manifestations', to='culture.typemanifestation')),
            ],
            options={
                'verbose_name': 'Manifestation',
                'db_table': 'culture"."manifestation',
            },
        ),
        migrations.CreateModel(
            name='GenreAutre',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=100)),
                ('datetime_proposition', models.DateTimeField()),
                ('statut', models.CharField(choices=[('en_attente', 'En attente de classement'), ('classee', 'Classée'), ('rejetee', "Rejetée (doublon d'une valeur existante)")], default='en_attente', max_length=50)),
                ('manifestation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='genre_autre_propositions', to='culture.manifestation')),
            ],
            options={
                'verbose_name': 'Genre (proposition Autre)',
                'db_table': 'culture"."genre_autre',
            },
        ),
        migrations.CreateModel(
            name='DimensionAutre',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=100)),
                ('datetime_proposition', models.DateTimeField()),
                ('statut', models.CharField(choices=[('en_attente', 'En attente de classement'), ('classee', 'Classée'), ('rejetee', "Rejetée (doublon d'une valeur existante)")], default='en_attente', max_length=50)),
                ('manifestation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dimension_autre_propositions', to='culture.manifestation')),
            ],
            options={
                'verbose_name': 'Dimension (proposition Autre)',
                'db_table': 'culture"."dimension_autre',
            },
        ),
        migrations.CreateModel(
            name='PeriodiciteAutre',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=100)),
                ('datetime_proposition', models.DateTimeField()),
                ('statut', models.CharField(choices=[('en_attente', 'En attente de classement'), ('classee', 'Classée'), ('rejetee', "Rejetée (doublon d'une valeur existante)")], default='en_attente', max_length=50)),
                ('manifestation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periodicite_autre_propositions', to='culture.manifestation')),
            ],
            options={
                'verbose_name': 'Périodicité (proposition Autre)',
                'db_table': 'culture"."periodicite_autre',
            },
        ),
        migrations.CreateModel(
            name='TypeEspaceAutre',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=100)),
                ('datetime_proposition', models.DateTimeField()),
                ('statut', models.CharField(choices=[('en_attente', 'En attente de classement'), ('classee', 'Classée'), ('rejetee', "Rejetée (doublon d'une valeur existante)")], default='en_attente', max_length=50)),
                ('manifestation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type_espace_autre_propositions', to='culture.manifestation')),
            ],
            options={
                'verbose_name': "Type d'espace (proposition Autre)",
                'db_table': 'culture"."type_espace_autre',
            },
        ),
        migrations.CreateModel(
            name='TypeManifestationAutre',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=100)),
                ('datetime_proposition', models.DateTimeField()),
                ('statut', models.CharField(choices=[('en_attente', 'En attente de classement'), ('classee', 'Classée'), ('rejetee', "Rejetée (doublon d'une valeur existante)")], default='en_attente', max_length=50)),
                ('manifestation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type_manifestation_autre_propositions', to='culture.manifestation')),
            ],
            options={
                'verbose_name': 'Type de manifestation (proposition Autre)',
                'db_table': 'culture"."type_manifestation_autre',
            },
        ),
        migrations.CreateModel(
            name='DemandeManifestation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('demande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manifestations_liees', to='gestion.demande')),
                ('manifestation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_liees', to='culture.manifestation')),
            ],
            options={
                'verbose_name': "Manifestation d'une demande",
                'db_table': 'culture"."demande_manifestation',
                'constraints': [models.UniqueConstraint(fields=('demande', 'manifestation'), name='uq_demande_manifestation')],
            },
        ),
    ]
